apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: 0e9yp7oiv-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/0e9yp7oiv-java-springboot-gitops